### ISSUE TITLE
Adding a hover effect to profile image and added my profile

### ISSUE THREAD

**Issue by Mudasir7-Prof-Snape** [oyepriyansh/DevProfiles#108] opened 2023-10-05 07:52 UTC
![Screenshot from 2023-10-05 13-15-47](https://github.com/oyepriyansh/DevProfiles/assets/140256749/50712def-a24e-4991-b55d-d84bd641fca0)

**Comment by oyepriyansh** [comment] 2023-10-05 08:05
Assigned to you

**Comment by Neeraaaj** [comment] 2023-10-05 11:12
@oyepriyansh hey, if the issue is still not fixed assign it to me!

**Comment by ojKunal** [comment] 2023-10-05 22:03
I would like to work on this issue . Please assign this issue to me.

**Closed** 2023-10-09 13:02 UTC
